#pragma once

#define AGENT_KILLER_TAG		'BEEF'
#define AGENT_KILLER_DEVICE	0x8000

#define AGENT_KILLER_ENUM_OBJ_PROCESS			CTL_CODE(AGENT_KILLER_DEVICE, 0x823, METHOD_NEITHER, FILE_ANY_ACCESS)
#define AGENT_KILLER_DISABLE_OBJ_PROCESS		CTL_CODE(AGENT_KILLER_DEVICE, 0x824, METHOD_NEITHER, FILE_ANY_ACCESS)
